### ISSUE TITLE
Why this restriction?

### ISSUE THREAD

**Issue by Arekusei** [ChiperSoft/QueryizeJS#1]
https://github.com/ChiperSoft/QueryizeJS/blob/master/lib/mutators.js#L1527

**Comment by ChiperSoft** [comment]
It's a safety check to make sure you aren't purging your entire table by accident. I made the assumption that if you were performing a delete that didn't have a where clause, your query could probably be better expressed through plain text.

If you _really_ need it you can just do a `.where(1)` to add a truthy condition to the where list.

**Comment by Arekusei** [comment]
Thanks for reply.


14.10.2016 19:25, Jarvis Badgley пишет:
> It's a safety check to make sure you aren't purging your entire table 
> by accident. I made the assumption that if you were performing a 
> delete that didn't have a where clause, your query could probably be 
> better expressed through plain text.
>
> If you _really_ need it you can just do a `.where(1)` to add a truthy 
> condition to the where list.
>

**Comment by Arekusei** [comment]
Then, still need to fix the string because it is not used in the removal 
request, and to request updating of the table.


14.10.2016 19:25, Jarvis Badgley пишет:
> It's a safety check to make sure you aren't purging your entire table 
> by accident. I made the assumption that if you were performing a 
> delete that didn't have a where clause, your query could probably be 
> better expressed through plain text.
>
> If you _really_ need it you can just do a `.where(1)` to add a truthy 
> condition to the where list.
>
